name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 167.235.77.17
          username: root
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            cd ~/server-infrastructure/portfolio-backend/ko2-kafka-events
            git pull
            cd ..
            docker compose rm -f ko2-kafka-events
            docker compose up --build -d ko2-kafka-events
